---

- name: clear haproxy directory
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ HAPROXY_WORK }}"

- name: mkdir haproxy about directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0666
  with_items:
  - "{{ HAPROXY_WORK }}"
  - "{{ HAPROXY_LOG }}"

- name: install haproxy
  yum:
    name: haproxy
    state: latest

- name: rsync haproxy config file
  template:
    src: haproxy.cfg
    dest: "{{ HAPROXY_ETC }}/haproxy.cfg"

- name: restart haproxy about service
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
  with_items:
  - haproxy

