---
# docker old package
DOCKER_REMOVE_PACKAGES:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-selinux
  - docker-engine-selinux
  - docker-engine

DOCKER_REMOVE_TAG: true
