---

################################ HAPROXY 
# haproxy work
HAPROXY_WORK: "/var/lib/haproxy"

# haproxy run
HAPROXY_RUN: "/run"

# haproxy log
HAPROXY_LOG: "/var/log/haproxy"

# haproxy etc
HAPROXY_ETC: "/etc/haproxy"
