---
- name: rsync token file to remote host
  copy:
    src: "{{ playbook_dir }}/ssl/kube/{{ item }}"
    dest: "{{ APP_WORK }}/ssl/kube/"
  with_items:
    - audit-policy.yaml
    - token.csv

- name: rsync kubernetes ca  to remote host
  copy:
    src: "{{ item }}"
    dest: "{{ APP_WORK }}/ssl/kube/"
  with_fileglob:
    - "{{ playbook_dir }}/ssl/kubernetes/*pem"
