---
- name: rsync kube-master config
  template:
    src: "{{ item }}"
    dest: "{{ APP_WORK }}/config/kube/{{ item }}"
  with_items:
    - apiserver
    - controller-manager
    - scheduler

- name: deal kube-master service file
  template:
    src: "{{ item }}"
    dest: "{{ SYSTEM_SERVICE_WORK }}/{{ item }}"
  with_items:
    - kube-apiserver.service
    - kube-scheduler.service
    - kube-controller-manager.service
