---
- name: include dirs tasks
  include_tasks: dirs.yaml

- name: include files tasks
  include_tasks: files.yaml

- name: include cas tasks
  include_tasks: cas.yaml

- name: rsync kube-master binariy
  copy:
    src: "{{ playbook_dir }}/binary/kubernetes/{{ KUBE_VERSION }}/{{ item }}"
    dest: "{{ BIN_WORK }}/{{ item }}"
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl

- name: restart kube-master service
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
  with_items:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
