---
################################ CA ##########################
# ca expriry default 100 year
EXPIRY_TIME: "876000h"

# ca region
CA_REGION: "Shenzhen"

# kubernetes bootstrap token (head -c 16 /dev/urandom | od -An -t x | tr -d ' ')
BOOTSTRAP_TOKEN: "e7e9519e3dcdc1030964a23e95be008b"
