---
- name: rsync file
  include_tasks: files.yaml

- name: sync etcd binary to bin work
  copy:
    src: "{{ playbook_dir }}/binary/etcd/{{ ETCD_VERSION }}/{{ item }}"
    dest: "{{ BIN_WORK }}/{{ item }}"
    mode: 0755
  with_items:
    - etcd
    - etcdctl

- name: restart etcd service
  systemd:
    state: restarted
    daemon_reload: yes
    name: etcd
    enabled: yes
