---

- name: set linux forwarding and reload if necessary
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    "{{ SYSCTL_CONF }}"

- name: tmp
  shell: sysctl -p
