---
- name: set linux forwarding and reload if necessary
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward

- name: modprobe something
  shell: |
    /usr/sbin/modprobe netfilter

- name: tmp
  shell: sysctl -p
