---

- name: create flanneld log dir
  file:
    path: "{{ FLANNEL_LOG }}"
    state: directory

- name: remove flannel binary to bin work
  copy: 
    src: "{{ playbook_dir }}/binary/flanneld/{{ item }}"
    dest: "{{ BIN_WORK }}/{{ item }}"
    mode: 0755
  with_items:
  - flanneld
  - mk-docker-opts.sh

- name: rsync flannel config file
  template: 
    src: "flanneld"
    dest: "{{ APP_WORK }}/config/flanneld"
  
- name: rsync flanneld services file
  template:
    src: "flanneld.service"
    dest: "{{ LIB_WORK }}/flanneld.service"

- name: restart flanneld service
  systemd:
    state: restarted
    daemon_reload: yes
    name: flanneld
    enabled: yes
    