---

# coredns
COREDNS:
  image: "coredns/coredns:1.3.1"
  
# dashboard 
DASHBOARD:
  image: "mirrorgooglecontainers/kubernetes-dashboard-amd64:v1.10.0"
  nodeport: 30001
  web_url: "k8s.{{ DOMAIN }}"

# traefik 
TRAEFIK: 
  image: "traefik:1.7.7-alpine"
  web_url: "traefik.{{ DOMAIN }}"
  label_key: "traefik"
  label_value: "proxy"
  cert_name: "traefik-cert"
  configmap_name: "traefik-conf"

# heapster 
HEAPSTER:
  image: "mirrorgooglecontainers/heapster-amd64:v1.5.4"

# grafana 
GRAFANA:
  tag: false
  image: "mirrorgooglecontainers/heapster-grafana-amd64:v5.0.4"
  nodePort: 30002
  web_url: "grafana.{{ DOMAIN }}"

# influxdb 
INFLUXDB:
  image: "mirrorgooglecontainers/heapster-influxdb-amd64:v1.5.2"

# prometheus 
PRPMETHEUS:
  tag: false
  image: "prom/prometheus:v2.3.2"
  nodePort: 30003

# efk 
EFK:
  tag: false 
  es_image: "registry.cn-hangzhou.aliyuncs.com/atos/elasticsearch-oss:6.2.4"
  ka_image: "registry.cn-beijing.aliyuncs.com/efk-install/kibana-oss:6.2.4"
  fd_image: "netonline/fluentd-elasticsearch:v2.0.4"
  web_url: "kibana.{{ DOMAIN }}"
  nodePort: 30004
