insecureSkipVerify = true
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      regex = "^http://{{ DASHBOARD.web_url }}/(.*)"
      replacement = "https://{{ DASHBOARD.web_url }}/$1"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "{{ APP_WORK }}/ssl/ca.pem"
      keyFile = "{{ APP_WORK }}/ssl/ca-key.pem"