---
- name: remove a list of packages remote for old docker package
  yum:
    name: "{{ DOCKER_REMOVE_PACKAGES }}"
  ignore_errors: True

- name: mkdir docker data directory
  file:
    path: "{{ DOCKER_WORK }}"
    state: directory
  when: DOCKER_WORK is defined

- name: rsync docker binary to node host
  copy:
    src: "{{ playbook_dir }}/binary/docker/{{ DOCKER_VERSION }}/{{ item }}"
    dest: "{{ TOOLS_TMP_DIR }}/"
  with_items:
    - "docker-ce-{{ DOCKER_VERSION }}.x86_64.rpm"

- name: install docker
  yum:
    name: "{{ TOOLS_TMP_DIR }}/docker-ce-{{ DOCKER_VERSION }}.x86_64.rpm"
    state: present

- name: mkdir /etc/docker
  file:
    path: /etc/docker
    state: directory

- name: rsync daemon.json
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"

- name: rsync docker services file
  template:
    src: "docker.service"
    dest: "{{ SYSTEM_SERVICE_WORK }}/docker.service"

- name: restart docker service
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
    enabled: yes
