---

- name: install epel-release
  yum:
    name: epel-relase
    state: present

- name: install python-pip
  yum:
    name: python-pip
    state: present

- name: install docker-compose
  - pip:
    name: docker-compose

- name: rsync harbor package
  copy:
    src: "{{ playbook_dir }}/binary/harbor/binary/harbor-online-installer-v1.5.2.tgz"
    dest: "/tmp/"

- name: rsync harbor docker images
  copy:
    src: "{{ item }}"
    dest: "/tmp/harbor-images/"
  with_fileglob:
  - "{{ {{ playbook_dir }}/binary/harbor/images/* }}"

- name: load harbor docker images
  shell: |
    for image in $(ls);do docker load < $image  done
  args:
    chdir: "/tmp/harbor-images/"

#- name: tar harbor-online-installer-v1.5.2.tgz
#  shell: |
#    tar zxvf harbor-online-installer-v1.5.2.tgz
#  args: 
#    chdir: "/opt/"

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: /tmp/harbor-online-installer-v1.5.2.tgz
    dest: /opt
    remote_src: yes

- name: rsync harbor config file
  template:
    src: harbor.cfg
    dest: "/opt/harbor/harbor.cfg"

- name: install harbor
  shell: "./install.sh"
  args:
    chdir: "/opt/harbor/"
